branch-defaults:
  feature/move-to-aws:
    environment: null
global:
  application_name: rakuichi-rakuza
  default_ec2_keyname: rakuichi-rakuza-id_rsa
  default_platform: PHP 5.5
  default_region: null
  profile: null
  sc: git
