branch-defaults:
  feature/move-to-aws:
    environment: rakuichi-rakuza-dev2
global:
  application_name: rakuichi-rakuza
  default_ec2_keyname: kori@aucfan.com
  default_platform: PHP 5.5
  default_region: null
  profile: null
  sc: git
