branch-defaults:
  master:
    environment: rakuichi-rakuza
  develop:
    environment: rakuichi-rakuza-dev
global:
  application_name: rakuichi-rakuza
  default_ec2_keyname: rakuichi-rakuza-id_rsa
  default_iam_instance_profile: rakuichi-rakuza-files-s3access
  default_platform: PHP 5.5
  default_region: null
  profile: null
  sc: git
