# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos64_min"
  # config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"
  config.vm.box_url = "http://192.168.101.62:8888/vagrant/CentOS-6.4-x86_64-v20130731.box"

  config.vm.define :web1 do |web|
    web.vm.network :private_network, ip: "192.168.33.101"
  end

  config.vm.synced_folder "../", "/var/www/html", :create => true, :owner=> 'vagrant', :group=>'vagrant', :mount_options => ['dmode=777,fmode=777']

  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "base"
    chef.add_recipe "php-mysql-httpd"
    chef.add_recipe "composer"
    chef.add_recipe "rakuichi-rakuza"
    chef.json = {
      :composer => {
        :install_path => "/usr/local/bin"
      }
    }
  end
end
