# A sample Gemfile
source "http://rubygems.org"

gem 'capistrano',           '=3.2.1'
gem 'railsless-deploy',     '=1.1.3'
gem 'capistrano-composer',  '=0.0.4'
gem 'librarian-chef'
gem 'knife-solo',           '=0.4.2'
gem 'serverspec'
gem 'compass'
