<?php
defined('FLEAMARKET_EVENT_SCHEDULE')            || define('FLEAMARKET_EVENT_SCHEDULE',            1);
defined('FLEAMARKET_EVENT_RESERVATION_RECEIPT') || define('FLEAMARKET_EVENT_RESERVATION_RECEIPT', 2);
defined('FLEAMARKET_EVENT_RECEIPT_END')         || define('FLEAMARKET_EVENT_RECEIPT_END',         3);
defined('FLEAMARKET_EVENT_CLOSE')               || define('FLEAMARKET_EVENT_CLOSE',               4);
defined('FLEAMARKET_EVENT_CANCEL')              || define('FLEAMARKET_EVENT_CANCEL',              5);

defined('FLEAMARKET_SHOP_FEE_FLAG_FREE')    || define('FLEAMARKET_SHOP_FEE_FLAG_FREE',   0);
defined('FLEAMARKET_SHOP_FEE_FLAG_CHARGE')  || define('FLEAMARKET_SHOP_FEE_FLAG_CHARGE', 1);

defined('FLEAMARKET_CAR_SHOP_FLAG_NG') || define('FLEAMARKET_CAR_SHOP_FLAG_NG', 0);
defined('FLEAMARKET_CAR_SHOP_FLAG_OK') || define('FLEAMARKET_CAR_SHOP_FLAG_OK', 1);

defined('FLEAMARKET_PRO_SHOP_FLAG_NG') || define('FLEAMARKET_PRO_SHOP_FLAG_NG', 0);
defined('FLEAMARKET_PRO_SHOP_FLAG_OK') || define('FLEAMARKET_PRO_SHOP_FLAG_OK', 1);

defined('FLEAMARKET_CHARGE_PARKING_FLAG_NONE')  || define('FLEAMARKET_CHARGE_PARKING_FLAG_NONE',  0);
defined('FLEAMARKET_CHARGE_PARKING_FLAG_EXIST') || define('FLEAMARKET_CHARGE_PARKING_FLAG_EXIST', 1);

defined('FLEAMARKET_FREE_PARKING_FLAG_NONE')    || define('FLEAMARKET_FREE_PARKING_FLAG_NONE',  0);
defined('FLEAMARKET_FREE_PARKING_FLAG_EXIST')   || define('FLEAMARKET_FREE_PARKING_FLAG_EXIST', 1);

defined('FLEAMARKET_RAINY_LOCATION_FLAG_NONE')  || define('FLEAMARKET_RAINY_LOCATION_FLAG_NONE',  0);
defined('FLEAMARKET_RAINY_LOCATION_FLAG_EXIST') || define('FLEAMARKET_RAINY_LOCATION_FLAG_EXIST', 1);

defined('FLEAMARKET_DISPLAY_FLAG_OFF')  || define('FLEAMARKET_DISPLAY_FLAG_OFF',    0);
defined('FLEAMARKET_DISPLAY_FLAG_ON')   || define('FLEAMARKET_DISPLAY_FLAG_ON',     1);

defined('FLEAMARKET_REGISTER_TYPE_ADMIN')   || define('FLEAMARKET_REGISTER_TYPE_ADMIN', 1);
defined('FLEAMARKET_REGISTER_TYPE_USER')    || define('FLEAMARKET_REGISTER_TYPE_USER',  2);

defined('LOCATION_REGISTER_TYPE_ADMIN') || define('LOCATION_REGISTER_TYPE_ADMIN',   1);
defined('LOCATION_REGISTER_TYPE_USER')  || define('LOCATION_REGISTER_TYPE_USER',    2);

defined('FLEAMARKET_ABOUT_ACCESS')       || define('FLEAMARKET_ABOUT_ACCESS',       1);
defined('FLEAMARKET_ABOUT_EVENT_TIME')   || define('FLEAMARKET_ABOUT_EVENT_TIME',   2);
defined('FLEAMARKET_ABOUT_BOOTH')        || define('FLEAMARKET_ABOUT_BOOTH',        3);
defined('FLEAMARKET_ABOUT_SHOP_STYLE')   || define('FLEAMARKET_ABOUT_SHOP_STYLE',   4);
defined('FLEAMARKET_ABOUT_SHOP_FEE')     || define('FLEAMARKET_ABOUT_SHOP_FEE',     5);
defined('FLEAMARKET_ABOUT_SHOP_CAUTION') || define('FLEAMARKET_ABOUT_SHOP_CAUTION', 6);
defined('FLEAMARKET_ABOUT_PARKING')      || define('FLEAMARKET_ABOUT_PARKING',      7);

return array();
