<?php

use \Model_Fleamarket;

$seeds = array(

    array(
        // 'fleamarket_id'       => 1,
        'location_id'         => 4,
        'group_code'          => 'A',
        'name'                => '越谷レイクタウンフリマ',
        'promoter_name'       => '株式会社オークファン',
        'event_number'        => 4,
        'event_date'          => '2014-04-01',
        'event_time_start'    => '08:35:00',
        'event_time_end'      => '15:45:00',
        'event_status'        => Model_fleamarket::EVENT_STATUS_RESERVATION_RECEIPT,
        'headline'            => 'テストフリマheadline!',
        'information'         => 'テストフリマinformation',
        'description'         => 'テスト用フリマ説明です',
        'reservation_serial'  => 111111,
        'reservation_start'   => '2014-03-11 15:46:53',
        'reservation_end'     => '2014-03-18 15:47:20',
        'reservation_tel'     => '03-1222-2222',
        'reservation_email'   => 'sample@aucfan.com',
        'website'             => 'http://www.yahoo.co.jp',
        'item_categories'     => '民芸品販売',
        // 'link_from_list'      => Model_fleamarket::,
        'pickup_flag'         => Model_fleamarket::PICKUP_FLAG_ON,
        'shop_fee_flag'       => Model_Fleamarket::SHOP_FEE_FLAG_FREE,
        'car_shop_flag'       => Model_fleamarket::CAR_SHOP_FLAG_OK,
        'pro_shop_flag'       => Model_fleamarket::PRO_SHOP_FLAG_OK,
        'charge_parking_flag' => Model_fleamarket::CHARGE_PARKING_FLAG_NONE,
        'free_parking_flag'   => Model_fleamarket::FREE_PARKING_FLAG_EXIST,
        'rainy_location_flag' => Model_fleamarket::RAINY_LOCATION_FLAG_NONE,
        // 'donation_fee'        => Model_fleamarket::,
        // 'donation_point'      => Model_fleamarket::,
        'register_type'       => Model_fleamarket::REGISTER_TYPE_USER,
        'display_flag'        => Model_fleamarket::DISPLAY_FLAG_ON,
        'created_user'        => 'somebody',
        'updated_user',
        'created_at'          => \Date::forge()->format('mysql'),
        // 'updated_at',
        // 'deleted_at',
    ),

    array(
        // 'fleamarket_id'       => 1,
        'location_id'         => 4,
        'group_code'          => 'A',
        'name'                => '国分寺フリマ',
        'promoter_name'       => '株式会社オークファン',
        'event_number'        => 4,
        'event_date'          => '2014-04-01',
        'event_time_start'    => '08:35:00',
        'event_time_end'      => '15:45:00',
        'event_status'        => Model_fleamarket::EVENT_STATUS_RESERVATION_RECEIPT,
        'headline'            => 'テストフリマheadline!',
        'information'         => 'テストフリマinformation',
        'description'         => 'テスト用フリマ説明です',
        'reservation_serial'  => 111111,
        'reservation_start'   => '2014-03-11 15:46:53',
        'reservation_end'     => '2014-03-18 15:47:20',
        'reservation_tel'     => '03-1222-2222',
        'reservation_email'   => 'sample@aucfan.com',
        'website'             => 'http://www.yahoo.co.jp',
        'item_categories'     => '民芸品販売',
        // 'link_from_list'      => Model_fleamarket::,
        'pickup_flag'         => Model_fleamarket::PICKUP_FLAG_ON,
        'shop_fee_flag'       => Model_Fleamarket::SHOP_FEE_FLAG_FREE,
        'car_shop_flag'       => Model_fleamarket::CAR_SHOP_FLAG_OK,
        'pro_shop_flag'       => Model_fleamarket::PRO_SHOP_FLAG_OK,
        'charge_parking_flag' => Model_fleamarket::CHARGE_PARKING_FLAG_NONE,
        'free_parking_flag'   => Model_fleamarket::FREE_PARKING_FLAG_EXIST,
        'rainy_location_flag' => Model_fleamarket::RAINY_LOCATION_FLAG_NONE,
        // 'donation_fee'        => Model_fleamarket::,
        // 'donation_point'      => Model_fleamarket::,
        'register_type'       => Model_fleamarket::REGISTER_TYPE_USER,
        'display_flag'        => Model_fleamarket::DISPLAY_FLAG_ON,
        'created_user'        => 'somebody',
        'updated_user',
        'created_at'          => \Date::forge()->format('mysql'),
        // 'updated_at',
        // 'deleted_at',
    ),

);

foreach ($seeds as $line) {
    $model = Model_Fleamarket::forge($line);
    $model->save();
}
